### ISSUE TITLE
1.16.4 error when stopping the server.

### ISSUE THREAD

**Issue by mindcloud69** [GoryMoon/GlobalGameRules#4]
forge-1.16.4-35.1.28
GlobalGameRules-1.16.4-5.0.0.1
I get the following errors when stopping the server. I believe it may be what is preventing my server from stopping cleanly.

[23:37:04] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file globalgamerules-common.toml of type COMMON for modid globalgamerules
[23:37:04] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:116)
[23:37:04] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]:         at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]: Caused by: com.electronwill.nightconfig.core.io.ParsingException: Table with path [gamerules] has been declared twice.
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at com.electronwill.nightconfig.toml.TomlParser.checkContainsOnlySubtables(TomlParser.java:136)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:93)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  at net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:112)
[23:37:04] [Thread-1/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:635]:  ... 1 more

**Comment by mindcloud69** [comment]
Issue still happening after I remove you mod. Closing
