### ISSUE TITLE
When the server turned on, it crashed

### ISSUE THREAD

**Issue by humonia-sys** [GoryMoon/GlobalGameRules#7]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 6/6/21 11:51 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.GameRules$RuleValue.func_223554_b(Lcom/mojang/brigadier/context/CommandContext;Ljava/lang/String;)V
	at se.gory_moon.globalgamerules.WorldEvents.lambda$onWorldLoad$2(WorldEvents.java:61) ~[globalgamerules:5.0.1.3] {re:classloading}
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_281] {}
	at se.gory_moon.globalgamerules.WorldEvents.onWorldLoad(WorldEvents.java:61) ~[globalgamerules:5.0.1.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_9_WorldEvents_onWorldLoad_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:430) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:351) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:721) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}

**Comment by GoryMoon** [comment]
It's strange why that happens, try this new https://www.curseforge.com/minecraft/mc-mods/global-gamerules/files/3378657
